name: Build and Push Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - sandbox
  pull_request:
    branches:
      - sandbox
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Checkout Bastillion Repository
      uses: actions/checkout@v4
      with:
        repository: lusky3/Bastillion
        path: Bastillion

    - name: Build with Maven
      run: |
        cd Bastillion
        mvn --batch-mode --update-snapshots clean package verify

    - name: Build Docker Image
      run: |
        cd Bastillion
        docker build -t bastillion:sandbox .

  push-to-registry:
    runs-on: ubuntu-24.04
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Checkout Bastillion Repository
      uses: actions/checkout@v4
      with:
        repository: lusky3/Bastillion
        path: Bastillion

    - name: Build with Maven
      run: |
        cd Bastillion
        mvn --batch-mode --update-snapshots clean package verify
    
    - name: Upload WAR file
      uses: actions/upload-artifact@v4
      with:
        name: bastillion-war
        path: target/bastillion-*.war

    - name: Build Docker Image
      run: |
        cd Bastillion
        docker build -t bastillion:sandbox .

    - name: Get Commit SHA
      id: vars
      run: echo "::set-output name=sha::$(git rev-parse --short=7 HEAD)"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image to GitHub Container Registry
      run: |
        docker tag bastillion:sandbox ghcr.io/${{ github.repository_owner }}/bastillion:sandbox
        docker tag bastillion:sandbox ghcr.io/${{ github.repository_owner }}/bastillion:${{ steps.vars.outputs.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/bastillion:sandbox
        docker push ghcr.io/${{ github.repository_owner }}/bastillion:${{ steps.vars.outputs.sha }}