name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to build the project during pull requests
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn --batch-mode --update-snapshots clean package verify

  # Job to upload the WAR file when changes are merged into main
  upload-war:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        mvn --batch-mode --update-snapshots clean package verify

    - name: Upload WAR file
      uses: actions/upload-artifact@v3
      with:
        name: bastillion-war
        path: target/bastillion-*.war
